spring:
  redis:
    host: 42.193.222.127
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    password: letletguanlaoshiRedis14
    timeout: 60000ms
server:
  port: 8026
  address: 127.0.0.1